### ISSUE TITLE
commenting /boot/config.txt render the system unbootable

### ISSUE THREAD

**Issue by marozsas** [josepsanzcamp/root-ro#4]
Hi, 

Your hint about reverting the changes by commenting the line "initramfs initrd.gz" line in the /boot/config.txt file renders the system unbootable, leaving the user at initramfs prompt.
I can't figure out a way to fix it after.

**Comment by josepsanzcamp** [comment]
Hi.

It's the first time that I hear this, when you comment the initramfs line in the config.txt, the system returns to the original state that runs without initrd.gz and by this reason, it must to boot as a factory install.

Could you provide me more detailed info when you are booting with the initramfs??? what raspbian release are you using??? dmesg output??? df -h output??? and the exact text that you see when you try to boot without initramfs???

Thanks in advance.

Josep.

**Comment by josepsanzcamp** [comment]
I close this issue by timeout!!!
